name: personal_expense_tracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  flex_color_picker: ^3.5.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  realm: ^3.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
